### ISSUE TITLE
Unexpected `---` error message

### ISSUE THREAD

**Issue by tedbauer** [cucapra/seashell#103]
This program:
```
let x = 2;
decl test: bit<32>[5];
```
throws this error:
```
[Error] [2.6] failure: '---' expected but 't' found

decl test: bit<32>[5];
     ^
```
which I think is a bug.

**Comment by rachitnigam** [comment]
`let` is a command. `decl`s need to be defined before the program command. The structure of a Fuse program is:
```
<funcdefs or record defs>
<decls>
<command>
```

**Comment by tedbauer** [comment]
Oops! Ok, I see.

**Comment by rachitnigam** [comment]
Added.

**Comment by tedbauer** [comment]
Would it be worth having an error message that mentions this explicitly? (Low priority of course!)

**Comment by rachitnigam** [comment]
This would be hard to do in  the parser (at least I don't know of a good way). Let's thing about this later,
