### ISSUE TITLE
Fix matadd_1dfullnrl.sea

### ISSUE THREAD

**Issue by tedbauer** [cucapra/seashell#11]
This case broke with re-implementation of index types. See comment in `matadd_1dfullnrl.sea` for details.

**Comment by sa2257** [comment]
Yes, Do you see any benefit of maintaining this example? I propose removing it. https://github.com/cucapra/seashell/tree/master/examples/docs

**Comment by rachitnigam** [comment]
Moved to https://github.com/cucapra/seashell/tree/master/test/skip
