### ISSUE TITLE
Buildbot UX improvements

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/seashell#118]
A few UX fixes for buildbot:

- [ ] Generate job name based on the `cpp` or `fuse` file in the provided archive.
- [ ] Change the format for "started" to "%MM/%DD, %TIME". Also the time currently given is 3 hours late.
- [ ] Add color labels for job states to quickly figure the status of recent jobs.
- [ ] Change job view to hide most build files under a fold and only focus on `rpt` files and archive files

**Comment by sampsyo** [comment]
@rachitnigam, I have a tracker for similar things already at #32. (The last thing on your list is the second bullet in the second group there.) Can you put your list there, please?

**Comment by rachitnigam** [comment]
Done
