### ISSUE TITLE
Int type inference behavior

### ISSUE THREAD

**Issue by tedbauer** [cucapra/seashell#123]
I'm a little unsure of whether or not #111 subsumes this, but right now, this program compiles just fine:
```
decl arr: bit<32>[10];

for (let i = 0..33) {
  arr[5] := i;
}
```
However, this program:
```
decl arr: bit<32>[10];

for (let i = 0..33) {
  arr[5] := i * 1;
}
```
(Only difference is the `* 1`.)
Throws this error:
```
Exception in thread "main" java.lang.RuntimeException: [Type error] [4.13] Expected subtype of int32 in assignment, received: int33.
  arr[5] := i * 1;
            ^
```
Is this the expected behavior?

**Comment by rachitnigam** [comment]
Try using an explicit let binding to get the types to work? See if that helps?

**Comment by tedbauer** [comment]
This program compiled successfully:
```
decl arr: bit<32>[10];

for (let i = 0..33) {
  let temp:bit<32> = 1;
  arr[5] := i * temp;
}
```
So there are ways to write this so it'll type check, but I wasn't sure if the error message from my first example was erroneous. Should the type be `bit<33>` like it says?

**Comment by rachitnigam** [comment]
This is a bug. Here is the offending code: https://github.com/cucapra/seashell/blob/f65229d3997af8e69974954da5daa8fb38207202/src/main/scala/Subtyping.scala#L78
