### ISSUE TITLE
Buildbot doesn't extract data

### ISSUE THREAD

**Issue by sa2257** [cucapra/seashell#146]
The current version of Buildbot seems to be not extracting data from reports. [job](http://gorgonzola.cs.cornell.edu:8000/jobs/Hlucp0gtlLc.html)

**Comment by rachitnigam** [comment]
Can you talk about expected behavior vs actual behavior? What is the data and where should buildbot extract it to?

**Comment by sa2257** [comment]
Expected behavior- extract data from reports after "synthesis" step and add them to worker logs.
This is a note to check which branch is running on Buildbot, whether it's missing data extraction PR and if so add it.

**Comment by rachitnigam** [comment]
Tracking in #32.
