### ISSUE TITLE
Character type for input data

### ISSUE THREAD

**Issue by tedbauer** [cucapra/seashell#151]
For the `nw` MachSuite app (Needleman–Wunsch, "a dynamic programming algorithm for optimal sequence alignment"), the input data consists of characters. (See [here][nw-data].) Would it be worth adding support for this?

[nw-data]: https://github.com/breagen/MachSuite/blob/master/nw/nw/input.data

**Comment by rachitnigam** [comment]
Chars can be encoded as ints. I guess this would be useful for the c++ backend.

**Comment by sampsyo** [comment]
A reasonable approach would be to have a special-case parser for characters that produces arrays of `bit<8>`s.

**Comment by rachitnigam** [comment]
Closing this for now since @tedbauer mentioned using cast to int works fine.
