### ISSUE TITLE
Index type addition does not work

### ISSUE THREAD

**Issue by sa2257** [cucapra/seashell#16]
Following program passes

```
func mmul(a: float[9 bank(3)], b: float[9 bank(3)], c: float[9 bank(3)]) {  
     for (let i = 0..3) unroll 1 {  
         for (let j = 0..3) unroll 3 {  
             c[i] := a[i*3+j] + b[i*3+j];  
         }  
     }  
}
```

But following fails with error `[Type error] can't apply operator '+' to idx<0 .. 1, -4611686018427387904 .. 4611686018427387903> and idx<0 .. 3, 0 .. 1>`

```
func mmul(a: float[9 bank(3)], b: float[9 bank(3)], c: float[9 bank(3)]) {  
    for (let i = 0..3) unroll 1 {  
        for (let j = 0..3) unroll 3 {  
            c[i*3+j] := a[i*3+j] + b[i*3+j];  
        }  
    }  
}
```
Shouldn't both give the same error?

**Comment by sampsyo** [comment]
Yo, @sa2257: for future reference, you can use a code block (```) to preserve line wrapping in pastes like these.

**Comment by sa2257** [comment]
Oh yes!! Thanks!

**Comment by rachitnigam** [comment]
Reassignment type checking was implemented incorrectly IMO. Both examples now fail on master. We need to formalize addition on index types before either example will work.

**Comment by rachitnigam** [comment]
Views subsume this
