### ISSUE TITLE
Buildbot- Possibility to display benchmark name in makefile jobs

### ISSUE THREAD

**Issue by sa2257** [cucapra/seashell#170]
Buildbot is agnostic of the `hw_basename` which makes this a little tricky. But if it can detect `KERNEL` in #166 we could use that.

**Comment by rachitnigam** [comment]
This is a small issue. Move to tracker please.

**Comment by rachitnigam** [comment]
Actually, this sounds the same as #167. What’s the difference between the two?

**Comment by sa2257** [comment]
> Actually, this sounds the same as #167. What’s the difference between the two?

Quite true. That was made as a bug report, and we decided its not a bug. 

> This is a small issue. Move to tracker please.

Implementation-wise maybe. But it makes Buildbot quite inconvenient to use.
