### ISSUE TITLE
Array creation construct

### ISSUE THREAD

**Issue by tedbauer** [cucapra/seashell#181]
Moving issue about possibly adding a Fuse construct from fuse-benchmarks here. Old issue: cucapra/fuse-benchmarks#40

**Comment by rachitnigam** [comment]
I'm working on views right now, but if @tedbauer you want to take a crack at this, I can provide help with it.

The high level changes needed are:
- Add AST node for array literals like records
- Change the parser to accept array literals.
- Add a `CLet(x, typ, init@EArrayLiteral(_))` rule that simply recursively emits the array. 
- Add codegeneration for array literals in the `CppLike` backend.

**Comment by tedbauer** [comment]
OK, I'll work on this.
