### ISSUE TITLE
Check why 'while expected'

### ISSUE THREAD

**Issue by sa2257** [cucapra/seashell#185]
```
decl m1: float[64][64];
decl m2: float[64][64];
decl prod: float[64][64];

for (let i = 0..64) {
    for (let j = 0..64) {
        for( let k = 0..64) {
            let v = prod[i][j];
            ---
            prod[i][j] := v + m1[i][k] * m2[k][j];
        }
    }
}
```

`[Parsing error] [16.1] failure: 'while' expected but ' ' found`

See why I get this error.

**Comment by rachitnigam** [comment]
Works fine for me on latest `master`. Try running `sbt assembly`.

**Comment by rachitnigam** [comment]
@sa2257 if this works for you, please close the issue.

**Comment by sa2257** [comment]
It seems like a whitespace or tab is giving out this error.
