### ISSUE TITLE
CircleCI not sensitive to seashell errors

### ISSUE THREAD

**Issue by sa2257** [cucapra/seashell#19]
CircleCI passes with programs that are not type checked. I recall they used to fail. Any clue why this is the case?

**Comment by rachitnigam** [comment]
@sa2257 Do you mean that circleCI doesn't fail when a program fails to typecheck? Or has this something to with the no typechecking flag.

**Comment by sa2257** [comment]
I just mean the former. It no longer fails when when a program fails to type check. But what is the no typechecking flag?

**Comment by rachitnigam** [comment]
Hm, seems like the error message gets redirected into the file. I'll make it print to stderr return the correct exit code.
