### ISSUE TITLE
Compiler doesn't seem to catch argument mismatch

### ISSUE THREAD

**Issue by sa2257** [cucapra/seashell#225]
This is fine I suppose. Just noting it down.

This passes the compiler
```
def aes_expandEncKey (k: ubit<8>[32], rc: ubit<8>, sbox: ubit<8>[256]){
}

...
aes_expandEncKey(key,rcon);
...
```

**Comment by rachitnigam** [comment]
Missing length check here in `EApp`: https://github.com/cucapra/seashell/blob/a781ac9cc6292caa6371d69c362f15a0d4b598d9/src/main/scala/typechecker/TypeCheck.scala#L262
