### ISSUE TITLE
Bank accessor must be static error for vsadd_nrl

### ISSUE THREAD

**Issue by sa2257** [cucapra/seashell#3]
https://github.com/cucapra/seashell/blob/master/examples/vsadd_nrl.sea fails due to "Bank accessor must be static error". (Simple examples for explicit access seem to work, array1d_physical.sea)

**Comment by rachitnigam** [comment]
Seems to be working now: https://github.com/cucapra/seashell/blob/master/test/test_programs.ml#L73
