### ISSUE TITLE
Sized ints overflow

### ISSUE THREAD

**Issue by tedbauer** [cucapra/seashell#37]
For the current implementation of sized integers, huge numbers are stored in the index types, and with bit numbers as high as 32 or so there are overflow errors. It seems a bit silly to store such big numbers, so maybe we could change the `TIndex` representation for the implementation? Would need to think about how to differentiate static ints I think.

**Comment by sampsyo** [comment]
Good point. One trick might be to store, for the range endpoints, _either_ a plain number _or_ a power of two:

```
type Offset = Lin of int | Exp of int
```

so `Exp 32` represents the number 2^32 while `Lin 32` represents plain old 32.

**Comment by rachitnigam** [comment]
@tedbauer is this fixed?

**Comment by rachitnigam** [comment]
@tedbauer ping

**Comment by rachitnigam** [comment]
Implemented in #46
