### ISSUE TITLE
Meaning of refresh banks in combine blocks

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/seashell#47]
What does this piece of code mean?
```
decl a: bit<16>[10 bank 2];
for (let i = 0..10) unroll 2 {
  let x = a[i];
} combine {
  sum += x;
  ---
  a[i]
}
```

Note: `---` is the new syntax for `%{ }%`

**Comment by rachitnigam** [comment]
Well, that's a different problem that I wasn't focusing on. In the implementation, a call to `---` returns all banks to all arrays. I'm asking if this should be the case when `---` is used inside a combine block.

**Comment by sampsyo** [comment]
Aha! Probably, so that this is allowed?

```
for (whatever) {
    irrelevant code;
} combine {
    b[0];
    ---
    b[0];
}
```

**Comment by rachitnigam** [comment]
Yeah, but it'll also allow:
```
for (i ...) {
  let x = a[i]
} combine {
  ---
  a[0] += x
}
```
which *might* be incorrect?
