### ISSUE TITLE
More loops

### ISSUE THREAD

**Issue by tedbauer** [cucapra/seashell#60]
Some of the MachSuite apps require loops that aren't supported in Fuse. AFAIK we only allow looping over ranges. Here are some loops that I think we can't write yet:

- ```while(a_idx>0 || b_idx>0) { ... }``` (From `nw/nw`, a "dynamic programming algorithm for optimal sequence alignment.") (Do we have boolean operators like "and" and "or"?)
- ```for(span=FFT_SIZE>>1; span; span>>=1, log++){ ... }``` (From `fft/strided`, a "recursive formulation of the Fast Fourier Transform.")

**Comment by rachitnigam** [comment]
Split into #63 and #72.
